language: php
cache:
  directories:
    - $HOME/.composer/cache
jobs:
  include:
    - php: 7.3
      env: PREFER_LOWEST=""
      before_script:
        - &composerupdate
          composer update --prefer-dist $PREFER_LOWEST
      script:
        - &phpunit
          "./vendor/bin/phpunit"
        - composer phpstan
      after_script:
        - ./vendor/bin/coveralls -v
    - php: 7.2
      env: PREFER_LOWEST=""
      before_script:
        - *composerupdate
      script:
        - *phpunit
    - php: 7.1
      env: PREFER_LOWEST=""
      before_script:
        - *composerupdate
      script:
        - *phpunit
